// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fib.proto

package l2

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FibEntry_Action int32

const (
	FibEntry_FORWARD FibEntry_Action = 0
	FibEntry_DROP    FibEntry_Action = 1
)

var FibEntry_Action_name = map[int32]string{
	0: "FORWARD",
	1: "DROP",
}
var FibEntry_Action_value = map[string]int32{
	"FORWARD": 0,
	"DROP":    1,
}

func (x FibEntry_Action) String() string {
	return proto.EnumName(FibEntry_Action_name, int32(x))
}
func (FibEntry_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fib_87f1b0eb59fc123b, []int{0, 0}
}

type FibEntry struct {
	PhysAddress             string          `protobuf:"bytes,1,opt,name=phys_address,json=physAddress,proto3" json:"phys_address,omitempty"`
	BridgeDomain            string          `protobuf:"bytes,2,opt,name=bridge_domain,json=bridgeDomain,proto3" json:"bridge_domain,omitempty"`
	Action                  FibEntry_Action `protobuf:"varint,3,opt,name=action,proto3,enum=l2.FibEntry_Action" json:"action,omitempty"`
	OutgoingInterface       string          `protobuf:"bytes,4,opt,name=outgoing_interface,json=outgoingInterface,proto3" json:"outgoing_interface,omitempty"`
	StaticConfig            bool            `protobuf:"varint,5,opt,name=static_config,json=staticConfig,proto3" json:"static_config,omitempty"`
	BridgedVirtualInterface bool            `protobuf:"varint,6,opt,name=bridged_virtual_interface,json=bridgedVirtualInterface,proto3" json:"bridged_virtual_interface,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}        `json:"-"`
	XXX_unrecognized        []byte          `json:"-"`
	XXX_sizecache           int32           `json:"-"`
}

func (m *FibEntry) Reset()         { *m = FibEntry{} }
func (m *FibEntry) String() string { return proto.CompactTextString(m) }
func (*FibEntry) ProtoMessage()    {}
func (*FibEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_fib_87f1b0eb59fc123b, []int{0}
}
func (m *FibEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibEntry.Unmarshal(m, b)
}
func (m *FibEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibEntry.Marshal(b, m, deterministic)
}
func (dst *FibEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibEntry.Merge(dst, src)
}
func (m *FibEntry) XXX_Size() int {
	return xxx_messageInfo_FibEntry.Size(m)
}
func (m *FibEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FibEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FibEntry proto.InternalMessageInfo

func (m *FibEntry) GetPhysAddress() string {
	if m != nil {
		return m.PhysAddress
	}
	return ""
}

func (m *FibEntry) GetBridgeDomain() string {
	if m != nil {
		return m.BridgeDomain
	}
	return ""
}

func (m *FibEntry) GetAction() FibEntry_Action {
	if m != nil {
		return m.Action
	}
	return FibEntry_FORWARD
}

func (m *FibEntry) GetOutgoingInterface() string {
	if m != nil {
		return m.OutgoingInterface
	}
	return ""
}

func (m *FibEntry) GetStaticConfig() bool {
	if m != nil {
		return m.StaticConfig
	}
	return false
}

func (m *FibEntry) GetBridgedVirtualInterface() bool {
	if m != nil {
		return m.BridgedVirtualInterface
	}
	return false
}

func init() {
	proto.RegisterType((*FibEntry)(nil), "l2.FibEntry")
	proto.RegisterEnum("l2.FibEntry_Action", FibEntry_Action_name, FibEntry_Action_value)
}

func init() { proto.RegisterFile("fib.proto", fileDescriptor_fib_87f1b0eb59fc123b) }

var fileDescriptor_fib_87f1b0eb59fc123b = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0x49, 0x29, 0x21, 0x7d, 0x0d, 0xa8, 0x98, 0x01, 0x33, 0x11, 0xca, 0x12, 0x09, 0x91,
	0x21, 0x6c, 0x6c, 0x11, 0xa1, 0x12, 0x53, 0x91, 0x07, 0x18, 0x2d, 0x27, 0x4e, 0xc2, 0x93, 0x82,
	0x5d, 0x39, 0x2e, 0x52, 0xff, 0x8a, 0x4f, 0x44, 0xb5, 0x1b, 0xc4, 0x7a, 0xce, 0xf5, 0xbb, 0x57,
	0x86, 0x59, 0x8b, 0x55, 0xb6, 0x31, 0xda, 0x6a, 0x32, 0xe9, 0xf3, 0xe5, 0xcf, 0x04, 0xa2, 0x15,
	0x56, 0x2f, 0xca, 0x9a, 0x1d, 0xb9, 0x85, 0x78, 0xf3, 0xb9, 0x1b, 0xb8, 0x90, 0xd2, 0x34, 0xc3,
	0x40, 0x83, 0x24, 0x48, 0x67, 0x6c, 0xbe, 0x67, 0x85, 0x47, 0xe4, 0x0e, 0xce, 0x2a, 0x83, 0xb2,
	0x6b, 0xb8, 0xd4, 0x5f, 0x02, 0x15, 0x9d, 0xb8, 0x4c, 0xec, 0x61, 0xe9, 0x18, 0xb9, 0x87, 0x50,
	0xd4, 0x16, 0xb5, 0xa2, 0xc7, 0x49, 0x90, 0x9e, 0xe7, 0x97, 0x59, 0x9f, 0x67, 0x63, 0x4b, 0x56,
	0x38, 0xc5, 0x0e, 0x11, 0xf2, 0x00, 0x44, 0x6f, 0x6d, 0xa7, 0x51, 0x75, 0x1c, 0x95, 0x6d, 0x4c,
	0x2b, 0xea, 0x86, 0x4e, 0xdd, 0xd9, 0x8b, 0xd1, 0xbc, 0x8e, 0x62, 0x3f, 0x60, 0xb0, 0xc2, 0x62,
	0xcd, 0x6b, 0xad, 0x5a, 0xec, 0xe8, 0x49, 0x12, 0xa4, 0x11, 0x8b, 0x3d, 0x7c, 0x76, 0x8c, 0x3c,
	0xc1, 0xb5, 0x1f, 0x24, 0xf9, 0x37, 0x1a, 0xbb, 0x15, 0xfd, 0xbf, 0xd3, 0xa1, 0x7b, 0x70, 0x75,
	0x08, 0xbc, 0x7b, 0xff, 0x57, 0xb0, 0xbc, 0x81, 0xd0, 0x2f, 0x24, 0x73, 0x38, 0x5d, 0xad, 0xd9,
	0x47, 0xc1, 0xca, 0xc5, 0x11, 0x89, 0x60, 0x5a, 0xb2, 0xf5, 0xdb, 0x22, 0xa8, 0x42, 0xf7, 0x7b,
	0x8f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xda, 0x93, 0x28, 0xba, 0x4a, 0x01, 0x00, 0x00,
}
