---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-agent-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 1000000000
    endpoints:
     - "172.17.0.1:22379"
  kafka.conf: |
    addrs:
     - "172.17.0.1:9092"
---
apiVersion: v1
kind: Pod
metadata:
  name: vnf-vpp
spec:
  containers:
    - name: "vnf-vpp"
      image: dev_vpp_agent
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - containerPort: 5002
      env:
        - name: MICROSERVICE_LABEL
          value: vnf-vpp
      volumeMounts:
        - name: vpp-config
          mountPath: /etc/vpp
        - name: agent-config
          mountPath: /opt/vpp-agent/dev
        - name: memif-sockets
          mountPath: /tmp
  volumes:
  - name: vpp-config
    configMap:
      name: vnf-vpp-cfg
  - name: agent-config
    configMap:
      name: vnf-agent-cfg
  - name: memif-sockets
    hostPath:
      path: /tmp
