issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
    - path: clientv2/vpp/dbadapter/data_resync_db.go
      linters:
        - staticcheck
      text: "SA4004:"
    - path: plugins/kvscheduler/plugin_scheduler.go
      linters:
        - staticcheck
      text: "SA2001:"
    - path: plugins/netalloc/netalloc_plugin.go
      linters:
        - staticcheck
      text: "SA1021:"
