apiVersion: v1
kind: Pod
metadata:
  name: etcdv3-server
spec:
  hostNetwork: true
  containers:
  - image: quay.io/coreos/etcd:v3.0.16
    name: etcdv3
    command:
    - /usr/local/bin/etcd
    - --advertise-client-urls 
    - http://0.0.0.0:22379
    - --listen-client-urls 
    - http://0.0.0.0:22379
    - --listen-peer-urls
    - http://0.0.0.0:22380
    ports:
    - containerPort: 22379
      hostPort: 22379
      name: serverport
    env:
      - name: ETCDCTL_API
        value: "3"
