FROM golang:1.17 as build

RUN env CGO_ENABLED=0 \
 	go build -ldflags='-s -w -extldflags "-static"' -o /test2json cmd/test2json

FROM ubuntu:20.04

RUN apt-get update && apt-get install -yq \
		curl \
		git \
		iproute2 \
		iputils-ping \
		make \
		nano \
		netcat \
		wget \
 	&& rm -rf /var/lib/apt/lists/*

# Install test tools
# - test2json
# - gotestsum

COPY --from=build /test2json /usr/local/bin/test2json

ARG GOTESTSUM_VERSION=1.8.1
RUN set -eux; \
	curl -fsSL https://github.com/gotestyourself/gotestsum/releases/download/v${GOTESTSUM_VERSION}/gotestsum_${GOTESTSUM_VERSION}_linux_amd64.tar.gz -o gotestsum.tar.gz; \
    tar -xf gotestsum.tar.gz gotestsum; \
    mv gotestsum /usr/local/bin/gotestsum; \
    rm gotestsum.tar.gz

COPY agentctl.test /usr/local/bin/agentctl
COPY e2e.test /

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
