// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/model.proto

package mymodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyModel struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mynum                int32    `protobuf:"varint,2,opt,name=mynum,proto3" json:"mynum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyModel) Reset()         { *m = MyModel{} }
func (m *MyModel) String() string { return proto.CompactTextString(m) }
func (*MyModel) ProtoMessage()    {}
func (*MyModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d10048d769ba1c4e, []int{0}
}

func (m *MyModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyModel.Unmarshal(m, b)
}
func (m *MyModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyModel.Marshal(b, m, deterministic)
}
func (m *MyModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyModel.Merge(m, src)
}
func (m *MyModel) XXX_Size() int {
	return xxx_messageInfo_MyModel.Size(m)
}
func (m *MyModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MyModel.DiscardUnknown(m)
}

var xxx_messageInfo_MyModel proto.InternalMessageInfo

func (m *MyModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MyModel) GetMynum() int32 {
	if m != nil {
		return m.Mynum
	}
	return 0
}

func init() {
	proto.RegisterType((*MyModel)(nil), "mymodel.MyModel")
}

func init() { proto.RegisterFile("proto/model.proto", fileDescriptor_d10048d769ba1c4e) }

var fileDescriptor_d10048d769ba1c4e = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcd, 0x4f, 0x49, 0xcd, 0xd1, 0x03, 0xb3, 0x85, 0xd8, 0x73, 0x2b, 0xc1, 0x5c,
	0x25, 0x63, 0x2e, 0x76, 0xdf, 0x4a, 0x5f, 0x10, 0x53, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37,
	0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0xcd, 0xad, 0xcc,
	0x2b, 0xcd, 0x95, 0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x92, 0xd8, 0xc0, 0x86, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06, 0x28, 0xd3, 0x2f, 0x59, 0x00, 0x00, 0x00,
}
