---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf1-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
    }
    cpu {
      main-core 26
      corelist-workers 27
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }
