// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.1
// source: ligato/configurator/statspoller.proto

package configurator

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	vpp "go.ligato.io/vpp-agent/v3/proto/ligato/vpp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Stats defines stats data returned by StatsPollerService.
type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stats:
	//	*Stats_VppStats
	Stats isStats_Stats `protobuf_oneof:"stats"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_configurator_statspoller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_configurator_statspoller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_ligato_configurator_statspoller_proto_rawDescGZIP(), []int{0}
}

func (m *Stats) GetStats() isStats_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (x *Stats) GetVppStats() *vpp.Stats {
	if x, ok := x.GetStats().(*Stats_VppStats); ok {
		return x.VppStats
	}
	return nil
}

type isStats_Stats interface {
	isStats_Stats()
}

type Stats_VppStats struct {
	VppStats *vpp.Stats `protobuf:"bytes,1,opt,name=vpp_stats,json=vppStats,proto3,oneof"`
}

func (*Stats_VppStats) isStats_Stats() {}

type PollStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PeriodSec defines polling period (in seconds). Set to zero to
	// return just single polling.
	PeriodSec uint32 `protobuf:"varint,1,opt,name=period_sec,json=periodSec,proto3" json:"period_sec,omitempty"`
	// NumPolls defines number of pollings. Set to non-zero number to
	// stop the polling after specified number of pollings is reached.
	NumPolls uint32 `protobuf:"varint,2,opt,name=num_polls,json=numPolls,proto3" json:"num_polls,omitempty"`
}

func (x *PollStatsRequest) Reset() {
	*x = PollStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_configurator_statspoller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollStatsRequest) ProtoMessage() {}

func (x *PollStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_configurator_statspoller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollStatsRequest.ProtoReflect.Descriptor instead.
func (*PollStatsRequest) Descriptor() ([]byte, []int) {
	return file_ligato_configurator_statspoller_proto_rawDescGZIP(), []int{1}
}

func (x *PollStatsRequest) GetPeriodSec() uint32 {
	if x != nil {
		return x.PeriodSec
	}
	return 0
}

func (x *PollStatsRequest) GetNumPolls() uint32 {
	if x != nil {
		return x.NumPolls
	}
	return 0
}

type PollStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PollSeq defines the sequence number of this polling response.
	PollSeq uint32 `protobuf:"varint,1,opt,name=poll_seq,json=pollSeq,proto3" json:"poll_seq,omitempty"`
	// Stats contains polled stats data.
	Stats *Stats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *PollStatsResponse) Reset() {
	*x = PollStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ligato_configurator_statspoller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollStatsResponse) ProtoMessage() {}

func (x *PollStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ligato_configurator_statspoller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollStatsResponse.ProtoReflect.Descriptor instead.
func (*PollStatsResponse) Descriptor() ([]byte, []int) {
	return file_ligato_configurator_statspoller_proto_rawDescGZIP(), []int{2}
}

func (x *PollStatsResponse) GetPollSeq() uint32 {
	if x != nil {
		return x.PollSeq
	}
	return 0
}

func (x *PollStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_ligato_configurator_statspoller_proto protoreflect.FileDescriptor

var file_ligato_configurator_statspoller_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x70, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x14, 0x6c, 0x69,
	0x67, 0x61, 0x74, 0x6f, 0x2f, 0x76, 0x70, 0x70, 0x2f, 0x76, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x42, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x76,
	0x70, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x76, 0x70, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x08, 0x76, 0x70, 0x70, 0x53, 0x74, 0x61, 0x74, 0x73, 0x42, 0x07, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x50, 0x6f, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d,
	0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75,
	0x6d, 0x50, 0x6f, 0x6c, 0x6c, 0x73, 0x22, 0x60, 0x0a, 0x11, 0x50, 0x6f, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x6f, 0x6c, 0x6c, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70,
	0x6f, 0x6c, 0x6c, 0x53, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x32, 0x74, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x50, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e,
	0x0a, 0x09, 0x50, 0x6f, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x25, 0x2e, 0x6c, 0x69,
	0x67, 0x61, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x42,
	0x5a, 0x40, 0x67, 0x6f, 0x2e, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2e, 0x69, 0x6f, 0x2f, 0x76,
	0x70, 0x70, 0x2d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6c, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ligato_configurator_statspoller_proto_rawDescOnce sync.Once
	file_ligato_configurator_statspoller_proto_rawDescData = file_ligato_configurator_statspoller_proto_rawDesc
)

func file_ligato_configurator_statspoller_proto_rawDescGZIP() []byte {
	file_ligato_configurator_statspoller_proto_rawDescOnce.Do(func() {
		file_ligato_configurator_statspoller_proto_rawDescData = protoimpl.X.CompressGZIP(file_ligato_configurator_statspoller_proto_rawDescData)
	})
	return file_ligato_configurator_statspoller_proto_rawDescData
}

var file_ligato_configurator_statspoller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ligato_configurator_statspoller_proto_goTypes = []interface{}{
	(*Stats)(nil),             // 0: ligato.configurator.Stats
	(*PollStatsRequest)(nil),  // 1: ligato.configurator.PollStatsRequest
	(*PollStatsResponse)(nil), // 2: ligato.configurator.PollStatsResponse
	(*vpp.Stats)(nil),         // 3: ligato.vpp.Stats
}
var file_ligato_configurator_statspoller_proto_depIdxs = []int32{
	3, // 0: ligato.configurator.Stats.vpp_stats:type_name -> ligato.vpp.Stats
	0, // 1: ligato.configurator.PollStatsResponse.stats:type_name -> ligato.configurator.Stats
	1, // 2: ligato.configurator.StatsPollerService.PollStats:input_type -> ligato.configurator.PollStatsRequest
	2, // 3: ligato.configurator.StatsPollerService.PollStats:output_type -> ligato.configurator.PollStatsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ligato_configurator_statspoller_proto_init() }
func file_ligato_configurator_statspoller_proto_init() {
	if File_ligato_configurator_statspoller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ligato_configurator_statspoller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ligato_configurator_statspoller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ligato_configurator_statspoller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ligato_configurator_statspoller_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Stats_VppStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ligato_configurator_statspoller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ligato_configurator_statspoller_proto_goTypes,
		DependencyIndexes: file_ligato_configurator_statspoller_proto_depIdxs,
		MessageInfos:      file_ligato_configurator_statspoller_proto_msgTypes,
	}.Build()
	File_ligato_configurator_statspoller_proto = out.File
	file_ligato_configurator_statspoller_proto_rawDesc = nil
	file_ligato_configurator_statspoller_proto_goTypes = nil
	file_ligato_configurator_statspoller_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StatsPollerServiceClient is the client API for StatsPollerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatsPollerServiceClient interface {
	// PollStats is used for polling stats with specific period and number of pollings.
	PollStats(ctx context.Context, in *PollStatsRequest, opts ...grpc.CallOption) (StatsPollerService_PollStatsClient, error)
}

type statsPollerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsPollerServiceClient(cc grpc.ClientConnInterface) StatsPollerServiceClient {
	return &statsPollerServiceClient{cc}
}

func (c *statsPollerServiceClient) PollStats(ctx context.Context, in *PollStatsRequest, opts ...grpc.CallOption) (StatsPollerService_PollStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StatsPollerService_serviceDesc.Streams[0], "/ligato.configurator.StatsPollerService/PollStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &statsPollerServicePollStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StatsPollerService_PollStatsClient interface {
	Recv() (*PollStatsResponse, error)
	grpc.ClientStream
}

type statsPollerServicePollStatsClient struct {
	grpc.ClientStream
}

func (x *statsPollerServicePollStatsClient) Recv() (*PollStatsResponse, error) {
	m := new(PollStatsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StatsPollerServiceServer is the server API for StatsPollerService service.
type StatsPollerServiceServer interface {
	// PollStats is used for polling stats with specific period and number of pollings.
	PollStats(*PollStatsRequest, StatsPollerService_PollStatsServer) error
}

// UnimplementedStatsPollerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatsPollerServiceServer struct {
}

func (*UnimplementedStatsPollerServiceServer) PollStats(*PollStatsRequest, StatsPollerService_PollStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method PollStats not implemented")
}

func RegisterStatsPollerServiceServer(s *grpc.Server, srv StatsPollerServiceServer) {
	s.RegisterService(&_StatsPollerService_serviceDesc, srv)
}

func _StatsPollerService_PollStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PollStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatsPollerServiceServer).PollStats(m, &statsPollerServicePollStatsServer{stream})
}

type StatsPollerService_PollStatsServer interface {
	Send(*PollStatsResponse) error
	grpc.ServerStream
}

type statsPollerServicePollStatsServer struct {
	grpc.ServerStream
}

func (x *statsPollerServicePollStatsServer) Send(m *PollStatsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StatsPollerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ligato.configurator.StatsPollerService",
	HandlerType: (*StatsPollerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollStats",
			Handler:       _StatsPollerService_PollStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ligato/configurator/statspoller.proto",
}
