// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ligato/vpp-agent/vpp/l3/arp.proto

package vpp_l3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ARPEntry struct {
	Interface            string   `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	IpAddress            string   `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	PhysAddress          string   `protobuf:"bytes,3,opt,name=phys_address,json=physAddress,proto3" json:"phys_address,omitempty"`
	Static               bool     `protobuf:"varint,4,opt,name=static,proto3" json:"static,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ARPEntry) Reset()         { *m = ARPEntry{} }
func (m *ARPEntry) String() string { return proto.CompactTextString(m) }
func (*ARPEntry) ProtoMessage()    {}
func (*ARPEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fbd39463784eb2b, []int{0}
}

func (m *ARPEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ARPEntry.Unmarshal(m, b)
}
func (m *ARPEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ARPEntry.Marshal(b, m, deterministic)
}
func (m *ARPEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ARPEntry.Merge(m, src)
}
func (m *ARPEntry) XXX_Size() int {
	return xxx_messageInfo_ARPEntry.Size(m)
}
func (m *ARPEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ARPEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ARPEntry proto.InternalMessageInfo

func (m *ARPEntry) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *ARPEntry) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *ARPEntry) GetPhysAddress() string {
	if m != nil {
		return m.PhysAddress
	}
	return ""
}

func (m *ARPEntry) GetStatic() bool {
	if m != nil {
		return m.Static
	}
	return false
}

func init() {
	proto.RegisterType((*ARPEntry)(nil), "ligato.vpp_agent.vpp.l3.ARPEntry")
}

func init() { proto.RegisterFile("ligato/vpp-agent/vpp/l3/arp.proto", fileDescriptor_3fbd39463784eb2b) }

var fileDescriptor_3fbd39463784eb2b = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcc, 0xc9, 0x4c, 0x4f,
	0x2c, 0xc9, 0xd7, 0x2f, 0x2b, 0x28, 0xd0, 0x4d, 0x4c, 0x4f, 0xcd, 0x2b, 0x01, 0xb1, 0xf4, 0x73,
	0x8c, 0xf5, 0x13, 0x8b, 0x0a, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4, 0x21, 0x4a, 0xf4,
	0xca, 0x0a, 0x0a, 0xe2, 0xc1, 0x4a, 0x40, 0x2c, 0xbd, 0x1c, 0x63, 0xa5, 0x26, 0x46, 0x2e, 0x0e,
	0xc7, 0xa0, 0x00, 0xd7, 0xbc, 0x92, 0xa2, 0x4a, 0x21, 0x19, 0x2e, 0xce, 0xcc, 0xbc, 0x92, 0xd4,
	0xa2, 0xb4, 0xc4, 0xe4, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80, 0x90, 0x2c,
	0x17, 0x57, 0x66, 0x41, 0x7c, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0x13, 0x54, 0xba,
	0xc0, 0x11, 0x22, 0x20, 0xa4, 0xc8, 0xc5, 0x53, 0x90, 0x51, 0x59, 0x0c, 0x57, 0xc0, 0x0c, 0x56,
	0xc0, 0x0d, 0x12, 0x83, 0x29, 0x11, 0xe3, 0x62, 0x2b, 0x2e, 0x49, 0x2c, 0xc9, 0x4c, 0x96, 0x60,
	0x51, 0x60, 0xd4, 0xe0, 0x08, 0x82, 0xf2, 0x9c, 0x1c, 0xa2, 0xec, 0xd2, 0xf3, 0xf5, 0xa0, 0x4e,
	0xcc, 0x44, 0xf1, 0x88, 0x91, 0x3e, 0xd8, 0x03, 0xfa, 0x38, 0xbc, 0x68, 0x0d, 0xf2, 0x50, 0x8e,
	0x71, 0x12, 0x1b, 0x58, 0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbc, 0xd4, 0xbf, 0x47, 0x0b,
	0x01, 0x00, 0x00,
}
