// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stn.proto

/*
Package stn is a generated protocol buffer package.

It is generated from these files:
	stn.proto

It has these top-level messages:
	StnRule
*/
package stn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StnRule struct {
	IpAdress  string `protobuf:"bytes,1,opt,name=ip_adress,json=ipAdress" json:"ip_adress,omitempty"`
	Interface string `protobuf:"bytes,2,opt,name=interface" json:"interface,omitempty"`
	RuleName  string `protobuf:"bytes,3,opt,name=rule_name,json=ruleName" json:"rule_name,omitempty"`
}

func (m *StnRule) Reset()                    { *m = StnRule{} }
func (m *StnRule) String() string            { return proto.CompactTextString(m) }
func (*StnRule) ProtoMessage()               {}
func (*StnRule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StnRule) GetIpAdress() string {
	if m != nil {
		return m.IpAdress
	}
	return ""
}

func (m *StnRule) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *StnRule) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func init() {
	proto.RegisterType((*StnRule)(nil), "stn.StnRule")
}

func init() { proto.RegisterFile("stn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2e, 0xc9, 0xd3,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2e, 0xc9, 0x53, 0x4a, 0xe4, 0x62, 0x0f, 0x2e,
	0xc9, 0x0b, 0x2a, 0xcd, 0x49, 0x15, 0x92, 0xe6, 0xe2, 0xcc, 0x2c, 0x88, 0x4f, 0x4c, 0x29, 0x4a,
	0x2d, 0x2e, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0xc8, 0x2c, 0x70, 0x04, 0xf3, 0x85,
	0x64, 0xb8, 0x38, 0x33, 0xf3, 0x4a, 0x52, 0x8b, 0xd2, 0x12, 0x93, 0x53, 0x25, 0x98, 0xc0, 0x92,
	0x08, 0x01, 0x90, 0xd6, 0xa2, 0xd2, 0x9c, 0xd4, 0xf8, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x66, 0x88,
	0x56, 0x90, 0x80, 0x5f, 0x62, 0x6e, 0x6a, 0x12, 0x1b, 0xd8, 0x3a, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa2, 0x98, 0xd8, 0x0e, 0x7b, 0x00, 0x00, 0x00,
}
