// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generic/model.proto

package generic

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ModelSpec defines a model specification to identify a model.
type ModelSpec struct {
	// Module describes grouping for the model.
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Version describes version of the model schema.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Type describes name of type described by this model.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Class describes purpose for the model.
	Class                string   `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelSpec) Reset()         { *m = ModelSpec{} }
func (m *ModelSpec) String() string { return proto.CompactTextString(m) }
func (*ModelSpec) ProtoMessage()    {}
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_40a7ce0838b26c3e, []int{0}
}

func (m *ModelSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelSpec.Unmarshal(m, b)
}
func (m *ModelSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelSpec.Marshal(b, m, deterministic)
}
func (m *ModelSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelSpec.Merge(m, src)
}
func (m *ModelSpec) XXX_Size() int {
	return xxx_messageInfo_ModelSpec.Size(m)
}
func (m *ModelSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ModelSpec proto.InternalMessageInfo

func (m *ModelSpec) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

func (m *ModelSpec) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ModelSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ModelSpec) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

// ModelDescriptor defines model descriptor to describe a model.
type ModelDescriptor struct {
	Spec *ModelSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// ProtoName is a name of protobuf message representing the model.
	ProtoName            string                    `protobuf:"bytes,2,opt,name=proto_name,json=protoName,proto3" json:"proto_name,omitempty"`
	Options              []*ModelDescriptor_Option `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ModelDescriptor) Reset()         { *m = ModelDescriptor{} }
func (m *ModelDescriptor) String() string { return proto.CompactTextString(m) }
func (*ModelDescriptor) ProtoMessage()    {}
func (*ModelDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_40a7ce0838b26c3e, []int{1}
}

func (m *ModelDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelDescriptor.Unmarshal(m, b)
}
func (m *ModelDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelDescriptor.Marshal(b, m, deterministic)
}
func (m *ModelDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelDescriptor.Merge(m, src)
}
func (m *ModelDescriptor) XXX_Size() int {
	return xxx_messageInfo_ModelDescriptor.Size(m)
}
func (m *ModelDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_ModelDescriptor proto.InternalMessageInfo

func (m *ModelDescriptor) GetSpec() *ModelSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *ModelDescriptor) GetProtoName() string {
	if m != nil {
		return m.ProtoName
	}
	return ""
}

func (m *ModelDescriptor) GetOptions() []*ModelDescriptor_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

type ModelDescriptor_Option struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values               []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelDescriptor_Option) Reset()         { *m = ModelDescriptor_Option{} }
func (m *ModelDescriptor_Option) String() string { return proto.CompactTextString(m) }
func (*ModelDescriptor_Option) ProtoMessage()    {}
func (*ModelDescriptor_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_40a7ce0838b26c3e, []int{1, 0}
}

func (m *ModelDescriptor_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelDescriptor_Option.Unmarshal(m, b)
}
func (m *ModelDescriptor_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelDescriptor_Option.Marshal(b, m, deterministic)
}
func (m *ModelDescriptor_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelDescriptor_Option.Merge(m, src)
}
func (m *ModelDescriptor_Option) XXX_Size() int {
	return xxx_messageInfo_ModelDescriptor_Option.Size(m)
}
func (m *ModelDescriptor_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelDescriptor_Option.DiscardUnknown(m)
}

var xxx_messageInfo_ModelDescriptor_Option proto.InternalMessageInfo

func (m *ModelDescriptor_Option) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ModelDescriptor_Option) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type KnownModelsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KnownModelsRequest) Reset()         { *m = KnownModelsRequest{} }
func (m *KnownModelsRequest) String() string { return proto.CompactTextString(m) }
func (*KnownModelsRequest) ProtoMessage()    {}
func (*KnownModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40a7ce0838b26c3e, []int{2}
}

func (m *KnownModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnownModelsRequest.Unmarshal(m, b)
}
func (m *KnownModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnownModelsRequest.Marshal(b, m, deterministic)
}
func (m *KnownModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnownModelsRequest.Merge(m, src)
}
func (m *KnownModelsRequest) XXX_Size() int {
	return xxx_messageInfo_KnownModelsRequest.Size(m)
}
func (m *KnownModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KnownModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KnownModelsRequest proto.InternalMessageInfo

type KnownModelsResponse struct {
	KnownModels          []*ModelDescriptor `protobuf:"bytes,1,rep,name=known_models,json=knownModels,proto3" json:"known_models,omitempty"`
	ActiveModules        []string           `protobuf:"bytes,2,rep,name=active_modules,json=activeModules,proto3" json:"active_modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KnownModelsResponse) Reset()         { *m = KnownModelsResponse{} }
func (m *KnownModelsResponse) String() string { return proto.CompactTextString(m) }
func (*KnownModelsResponse) ProtoMessage()    {}
func (*KnownModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_40a7ce0838b26c3e, []int{3}
}

func (m *KnownModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KnownModelsResponse.Unmarshal(m, b)
}
func (m *KnownModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KnownModelsResponse.Marshal(b, m, deterministic)
}
func (m *KnownModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KnownModelsResponse.Merge(m, src)
}
func (m *KnownModelsResponse) XXX_Size() int {
	return xxx_messageInfo_KnownModelsResponse.Size(m)
}
func (m *KnownModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KnownModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KnownModelsResponse proto.InternalMessageInfo

func (m *KnownModelsResponse) GetKnownModels() []*ModelDescriptor {
	if m != nil {
		return m.KnownModels
	}
	return nil
}

func (m *KnownModelsResponse) GetActiveModules() []string {
	if m != nil {
		return m.ActiveModules
	}
	return nil
}

func init() {
	proto.RegisterType((*ModelSpec)(nil), "generic.ModelSpec")
	proto.RegisterType((*ModelDescriptor)(nil), "generic.ModelDescriptor")
	proto.RegisterType((*ModelDescriptor_Option)(nil), "generic.ModelDescriptor.Option")
	proto.RegisterType((*KnownModelsRequest)(nil), "generic.KnownModelsRequest")
	proto.RegisterType((*KnownModelsResponse)(nil), "generic.KnownModelsResponse")
}

func init() { proto.RegisterFile("generic/model.proto", fileDescriptor_40a7ce0838b26c3e) }

var fileDescriptor_40a7ce0838b26c3e = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x0b, 0xd3, 0x30,
	0x14, 0xc7, 0xe9, 0x3a, 0x37, 0xf6, 0xea, 0x2f, 0xde, 0x86, 0x84, 0xa9, 0x38, 0x0a, 0xea, 0x3c,
	0xd8, 0x42, 0x3d, 0x89, 0x37, 0xf1, 0x20, 0xc8, 0x14, 0xba, 0x83, 0xe0, 0x65, 0x64, 0xd9, 0xa3,
	0x86, 0xb5, 0x49, 0x6c, 0xd2, 0xca, 0xfe, 0x42, 0xff, 0x2d, 0x69, 0xda, 0x6d, 0x0e, 0xf5, 0x96,
	0xf7, 0x79, 0xe9, 0xfb, 0x7e, 0xfa, 0x02, 0xf3, 0x82, 0x14, 0xd5, 0x52, 0xa4, 0x95, 0x3e, 0x50,
	0x99, 0x98, 0x5a, 0x3b, 0x8d, 0xd3, 0x01, 0xc6, 0x05, 0xcc, 0x36, 0x1d, 0xdf, 0x1a, 0x12, 0xf8,
	0x08, 0x26, 0x95, 0x3e, 0x34, 0x25, 0xb1, 0x60, 0x15, 0xac, 0x67, 0xf9, 0x50, 0x21, 0x83, 0x69,
	0x4b, 0xb5, 0x95, 0x5a, 0xb1, 0x91, 0x6f, 0x9c, 0x4b, 0x44, 0x18, 0xbb, 0x93, 0x21, 0x16, 0x7a,
	0xec, 0xcf, 0xb8, 0x80, 0x3b, 0xa2, 0xe4, 0xd6, 0xb2, 0xb1, 0x87, 0x7d, 0x11, 0xff, 0x0a, 0xe0,
	0x81, 0x4f, 0xfa, 0x40, 0x56, 0xd4, 0xd2, 0x38, 0x5d, 0xe3, 0x0b, 0x18, 0x5b, 0x43, 0xc2, 0xa7,
	0x45, 0x19, 0x26, 0x83, 0x54, 0x72, 0x31, 0xca, 0x7d, 0x1f, 0x9f, 0x02, 0x78, 0xed, 0x9d, 0xe2,
	0x15, 0x0d, 0x0a, 0x33, 0x4f, 0x3e, 0xf3, 0x8a, 0xf0, 0x2d, 0x4c, 0xb5, 0x71, 0x52, 0x2b, 0xcb,
	0xc2, 0x55, 0xb8, 0x8e, 0xb2, 0x67, 0xb7, 0x93, 0xae, 0x89, 0xc9, 0x17, 0x7f, 0x2f, 0x3f, 0xdf,
	0x5f, 0x66, 0x30, 0xe9, 0x11, 0x3e, 0x84, 0xf0, 0x48, 0xa7, 0xe1, 0xc7, 0xbb, 0x63, 0xb7, 0x8d,
	0x96, 0x97, 0x0d, 0x59, 0x36, 0x5a, 0x85, 0xdd, 0x36, 0xfa, 0x2a, 0x5e, 0x00, 0x7e, 0x52, 0xfa,
	0xa7, 0xf2, 0xb3, 0x6d, 0x4e, 0x3f, 0x1a, 0xb2, 0x2e, 0x3e, 0xc1, 0xfc, 0x86, 0x5a, 0xa3, 0x95,
	0x25, 0x7c, 0x07, 0x77, 0x8f, 0x1d, 0xde, 0xf9, 0xed, 0x5b, 0x16, 0x78, 0x41, 0xf6, 0x3f, 0xc1,
	0x3c, 0x3a, 0x5e, 0x87, 0xe0, 0x73, 0xb8, 0xcf, 0x85, 0x93, 0x2d, 0xed, 0xfa, 0x87, 0x38, 0x9b,
	0xdc, 0xeb, 0xe9, 0xa6, 0x87, 0xd9, 0x57, 0x88, 0x36, 0xe4, 0xf8, 0x96, 0xea, 0x56, 0x0a, 0xc2,
	0x8f, 0x10, 0xfd, 0x61, 0x82, 0x8f, 0x2f, 0x59, 0x7f, 0x5b, 0x2f, 0x9f, 0xfc, 0xbb, 0xd9, 0xcb,
	0xbf, 0x7f, 0xf5, 0xed, 0x65, 0x21, 0xdd, 0xf7, 0x66, 0x9f, 0x08, 0x5d, 0xa5, 0xa5, 0x2c, 0xb8,
	0xd3, 0x69, 0x6b, 0xcc, 0x6b, 0x5e, 0x90, 0x72, 0x29, 0x37, 0x32, 0x1d, 0x3e, 0xdf, 0x4f, 0xfc,
	0x73, 0xbc, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x01, 0xf7, 0xf9, 0x0a, 0x6e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaServiceClient interface {
	// KnownModels returns information about service capabilities
	// including list of models supported by the server.
	KnownModels(ctx context.Context, in *KnownModelsRequest, opts ...grpc.CallOption) (*KnownModelsResponse, error)
}

type metaServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetaServiceClient(cc *grpc.ClientConn) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) KnownModels(ctx context.Context, in *KnownModelsRequest, opts ...grpc.CallOption) (*KnownModelsResponse, error) {
	out := new(KnownModelsResponse)
	err := c.cc.Invoke(ctx, "/generic.MetaService/KnownModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
type MetaServiceServer interface {
	// KnownModels returns information about service capabilities
	// including list of models supported by the server.
	KnownModels(context.Context, *KnownModelsRequest) (*KnownModelsResponse, error)
}

// UnimplementedMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (*UnimplementedMetaServiceServer) KnownModels(ctx context.Context, req *KnownModelsRequest) (*KnownModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnownModels not implemented")
}

func RegisterMetaServiceServer(s *grpc.Server, srv MetaServiceServer) {
	s.RegisterService(&_MetaService_serviceDesc, srv)
}

func _MetaService_KnownModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnownModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).KnownModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic.MetaService/KnownModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).KnownModels(ctx, req.(*KnownModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generic.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KnownModels",
			Handler:    _MetaService_KnownModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generic/model.proto",
}
