// Code generated by protoc-gen-gogo.
// source: l3.proto
// DO NOT EDIT!

/*
Package l3 is a generated protocol buffer package.

It is generated from these files:
	l3.proto

It has these top-level messages:
	StaticRoutes
*/
package l3

import proto "github.com/gogo/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type StaticRoutes struct {
	Route []*StaticRoutes_Route `protobuf:"bytes,1,rep,name=route" json:"route,omitempty"`
}

func (m *StaticRoutes) Reset()         { *m = StaticRoutes{} }
func (m *StaticRoutes) String() string { return proto.CompactTextString(m) }
func (*StaticRoutes) ProtoMessage()    {}

func (m *StaticRoutes) GetRoute() []*StaticRoutes_Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type StaticRoutes_Route struct {
	VrfId             uint32 `protobuf:"varint,1,opt,name=vrf_id,proto3" json:"vrf_id,omitempty"`
	Description       string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DstIpAddr         string `protobuf:"bytes,3,opt,name=dst_ip_addr,proto3" json:"dst_ip_addr,omitempty"`
	NextHopAddr       string `protobuf:"bytes,4,opt,name=next_hop_addr,proto3" json:"next_hop_addr,omitempty"`
	OutgoingInterface string `protobuf:"bytes,5,opt,name=outgoing_interface,proto3" json:"outgoing_interface,omitempty"`
	Weight            uint32 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Preference        uint32 `protobuf:"varint,7,opt,name=preference,proto3" json:"preference,omitempty"`
}

func (m *StaticRoutes_Route) Reset()         { *m = StaticRoutes_Route{} }
func (m *StaticRoutes_Route) String() string { return proto.CompactTextString(m) }
func (*StaticRoutes_Route) ProtoMessage()    {}
