apiVersion: v1
kind: Pod
metadata:
  name: vswitch-vpp
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: "vswitch"
      image: ligato/vpp-agent
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      ports:
        - containerPort: 5002
        - containerPort: 9191
      readinessProbe:
        httpGet:
          path: /readiness
          port: 9191
        periodSeconds: 1
      livenessProbe:
        httpGet:
          path: /liveness
          port: 9191
        periodSeconds: 1
        initialDelaySeconds: 15
      env:
        - name: MICROSERVICE_LABEL
          value: vswitch
      volumeMounts:
        - name: vpp-config
          mountPath: /etc/vpp
        - name: agent-config
          mountPath: /opt/vpp-agent/dev
        - name: memif-sockets
          mountPath: /tmp
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
  - name: vpp-config
    configMap:
      name: vswitch-vpp-cfg
  - name: agent-config
    configMap:
      name: vswitch-agent-cfg
  - name: memif-sockets
    hostPath:
      path: /tmp
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock

