name: Build Images

on:
  push:
    branches: master
  pull_request:
    branches: master
  release:

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
  
  steps:
  - uses: actions/checkout@v1
  
  - name: Build
    run: |
      make images

  - name: Deploy
    run: |
      docker images
      
