---
name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    name: "Integration - VPP ${{ matrix.version }}"
    runs-on: ubuntu-latest
    env:
      VPP_VERSION: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: ['2106', '2101', '2009', '2005']

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Run tests"
        run: |
          make integration-tests

  e2e:
    name: "E2E - VPP ${{ matrix.version }}"
    runs-on: ubuntu-latest
    env:
      VPP_VERSION: ${{ matrix.version }}
      GOTESTSUM_JUNITFILE: /testreport/e2e.xml
    strategy:
      fail-fast: false
      matrix:
        version: ['2106', '2101', '2009', '2005']

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Dump Info"
        run: |
          env | sort
          ls -Al /sys/module

      - name: "Run Tests"
        run: |
          make e2e-tests

      - name: "Upload Test Results"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: E2E Test Results (VPP ${{ matrix.version }})
          path: ./tests/e2e/reports/e2e.xml
        run: |
          ls -Al ./tests/e2e/reports

  publish-test-results:
    name: "Publish Test Results"
    needs: e2e
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: "Publish Unit Test Results"
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
